version: "3.7"
services:
  hangman-answers:
    build:
      context: ./hangman_answers
    ports:
      - 5000:5000
  hangman-client:
    build:
      context: ./hangman_client
    depends_on:
      - "hangman-answers"
    environment:
      HANGMAN_ANSWERS_HOST: "hangman-answers"
    command: sleep 1d

